# Generated by Django 3.0 on 2019-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='videoFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='videoURL',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
